site:
  title: Rancher product documentation
  start_page: latest@rancher-manager:en:about-rancher/what-is-rancher.adoc
  url: https://documentation.suse.com/cloudnative

content:
  sources:
    - url: https://github.com/rancher/fleet-product-docs.git # en
      branches: [main]
      start_paths: [versions/v0.12]
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher
    # url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    # snapshot: true
  # supplemental_files: ./product-docs-supplemental-files
runtime:
  fetch: true
asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
    kw-build-type: 'product' # One of 'community' or 'product'
    kw-product-name: 'SUSE® Rancher Prime: Admission Policy Manager (Kubewarden)'
    kw-community-name: 'Kubewarden'
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ja, zh] # ko not supported by extension
    index_latest_only: true
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>

output:
  dir: build/site
